import { readFile } from "node:fs/promises";
import { HostIntegrationError } from "../core/errors.js";
import { writeTextAtomic } from "./atomic-file.js";
import type { HostIntegrationStatus, HostMcpServerCommand } from "./types.js";

const START = "// OPENWIKI:PI-EXTENSION:START";
const END = "// OPENWIKI:PI-EXTENSION:END";

interface MarkerRange {
  start: number;
  end: number;
}

/**
 * Renders the canonical managed Pi extension block.
 *
 * @param entry - Exact executable invocation to render.
 * @returns Complete marker-delimited TypeScript extension block.
 */
export function renderPiExtension(entry: HostMcpServerCommand): string {
  const commandJson = JSON.stringify(entry.command);
  const argsJson = JSON.stringify(entry.args);
  return `${START}
// Generated by OpenWiki. Do not edit directly.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawn, type ChildProcess } from "node:child_process";
import { createInterface } from "node:readline";

const MCP_COMMAND = ${commandJson};
const MCP_ARGS = ${argsJson};

export default function (pi: ExtensionAPI) {
  let child: ChildProcess | null = null;
  let nextId = 1;
  const pending = new Map<number, PromiseWithResolvers<Record<string, unknown>>>();
  let initialized: Promise<void> | null = null;

  function ensureProcess(): ChildProcess {
    if (child && child.exitCode === null) return child;
    child = spawn(MCP_COMMAND, MCP_ARGS, {
      stdio: ["pipe", "pipe", "inherit"],
    });

    const rl = createInterface({ input: child.stdout! });
    rl.on("line", (line) => {
      try {
        const msg = JSON.parse(line);
        if (msg.id !== undefined && pending.has(msg.id)) {
          const resolvers = pending.get(msg.id)!;
          pending.delete(msg.id);
          if (msg.error) {
            resolvers.reject(new Error(msg.error.message || JSON.stringify(msg.error)));
          } else {
            resolvers.resolve((msg.result as Record<string, unknown>) ?? {});
          }
        }
      } catch {
        // Ignore non-JSON output from stdout
      }
    });

    child.on("exit", () => {
      for (const [, resolvers] of pending) {
        resolvers.reject(new Error("OpenWiki MCP process exited"));
      }
      pending.clear();
      child = null;
      initialized = null;
    });

    child.on("error", (err) => {
      for (const [, resolvers] of pending) {
        resolvers.reject(err);
      }
      pending.clear();
      child = null;
      initialized = null;
    });

    return child;
  }

  async function callMcp(method: string, params?: Record<string, unknown>): Promise<Record<string, unknown>> {
    const proc = ensureProcess();
    const id = nextId++;
    const resolvers = Promise.withResolvers<Record<string, unknown>>();
    pending.set(id, resolvers);
    proc.stdin!.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\\n");
    return resolvers.promise;
  }

  async function ensureInitialized(): Promise<void> {
    if (!initialized) {
      initialized = (async () => {
        await callMcp("initialize", {
          protocolVersion: "2024-11-05",
          capabilities: {},
          clientInfo: { name: "openwiki-pi-extension", version: "1.0.0" },
        });
        const proc = ensureProcess();
        proc.stdin!.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }) + "\\n");
      })();
    }
    return initialized;
  }

  async function callTool(name: string, args: Record<string, unknown>, signal?: AbortSignal) {
    if (signal?.aborted) {
      return { content: [{ type: "text", text: "Tool call cancelled" }], details: {} };
    }
    await ensureInitialized();
    const result = await callMcp("tools/call", { name, arguments: args });
    const content = Array.isArray(result?.content) ? result.content : [{ type: "text", text: JSON.stringify(result) }];
    return {
      content,
      details: result ?? {},
    };
  }

  pi.on("session_shutdown", async () => {
    if (child && child.exitCode === null) {
      child.kill("SIGTERM");
      child = null;
    }
  });

  pi.registerCommand("openwiki", {
    description: "Display OpenWiki tool registration status",
    handler: async (_args, ctx) => {
      ctx.ui.notify(
        "OpenWiki tools registered: openwiki_begin, openwiki_submit_plan, openwiki_next_page, openwiki_inspect_page_claims, openwiki_submit_page, openwiki_finish",
        "info",
      );
    },
  });

  pi.registerTool({
    name: "openwiki_begin",
    label: "OpenWiki: Begin",
    description: "Start or resume OpenWiki repository generation.",
    parameters: Type.Object({
      root: Type.String({ description: "Absolute path to Git repository root" }),
      mode: Type.String({ description: "Lifecycle mode: 'init' or 'update'" }),
      language: Type.Optional(Type.String({ description: 'Optional BCP-47 code, e.g. "ko"' })),
      force: Type.Optional(Type.Boolean({ description: "Bypass update no-op detection" })),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_begin", params as Record<string, unknown>, signal);
    },
  });

  pi.registerTool({
    name: "openwiki_submit_plan",
    label: "OpenWiki: Submit Plan",
    description: "Submit the planned pages for repository documentation.",
    parameters: Type.Object({
      runId: Type.String({ description: "Active run ID returned by openwiki_begin" }),
      pages: Type.Array(
        Type.Object({
          path: Type.String({ description: "Canonical page path, e.g. 'openwiki/quickstart.md'" }),
          title: Type.String({ description: "Page title" }),
          purpose: Type.String({ description: "Page purpose and scope" }),
          seedPaths: Type.Optional(Type.Array(Type.String())),
          relatedPages: Type.Optional(Type.Array(Type.String())),
          instructions: Type.Optional(Type.Array(Type.String())),
        }),
        { description: "List of planned factual documentation pages" },
      ),
      deletePages: Type.Optional(
        Type.Array(Type.String(), { description: "Optional page paths to delete during update" }),
      ),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_submit_plan", params as Record<string, unknown>, signal);
    },
  });

  pi.registerTool({
    name: "openwiki_next_page",
    label: "OpenWiki: Next Page",
    description: "Advance to the next page job in the active run.",
    parameters: Type.Object({
      runId: Type.String({ description: "Active run ID" }),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_next_page", params as Record<string, unknown>, signal);
    },
  });

  pi.registerTool({
    name: "openwiki_inspect_page_claims",
    label: "OpenWiki: Inspect Page Claims",
    description: "Inspect existing claims for the pending page job.",
    parameters: Type.Object({
      runId: Type.String({ description: "Active run ID" }),
      jobId: Type.String({ description: "Active job ID from openwiki_next_page" }),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_inspect_page_claims", params as Record<string, unknown>, signal);
    },
  });

  pi.registerTool({
    name: "openwiki_submit_page",
    label: "OpenWiki: Submit Page",
    description: "Finalize a page job with claims decisions.",
    parameters: Type.Object({
      runId: Type.String({ description: "Active run ID" }),
      jobId: Type.String({ description: "Active job ID from openwiki_next_page" }),
      confirmedClaimIds: Type.Optional(Type.Array(Type.String())),
      claims: Type.Optional(
        Type.Array(
          Type.Object({
            id: Type.Optional(Type.String()),
            statement: Type.String(),
            evidence: Type.Array(Type.Object({ resource: Type.String() })),
          }),
        ),
      ),
      retractedClaimIds: Type.Optional(Type.Array(Type.String())),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_submit_page", params as Record<string, unknown>, signal);
    },
  });

  pi.registerTool({
    name: "openwiki_finish",
    label: "OpenWiki: Finish",
    description: "Complete the documentation run and write manifest.",
    parameters: Type.Object({
      runId: Type.String({ description: "Active run ID" }),
    }),
    async execute(_id, params, signal) {
      return callTool("openwiki_finish", params as Record<string, unknown>, signal);
    },
  });
}
${END}
`;
}

function hasUnmanagedOpenWikiCode(
  content: string,
  managed?: MarkerRange,
): boolean {
  for (const match of content.matchAll(/openwiki_begin/gmu)) {
    const index = match.index;
    if (!managed || index < managed.start || index >= managed.end) return true;
  }
  return false;
}

function markerRange(content: string): MarkerRange | null {
  const start = content.indexOf(START);
  const endMarker = content.indexOf(END);
  if (start === -1 && endMarker === -1) return null;
  if (start === -1 || endMarker === -1 || endMarker < start) {
    throw new HostIntegrationError(
      "invalid_input",
      "OpenWiki extension markers are incomplete or out of order.",
    );
  }
  if (
    content.indexOf(START, start + START.length) !== -1 ||
    content.indexOf(END, endMarker + END.length) !== -1
  ) {
    throw new HostIntegrationError(
      "invalid_input",
      "Multiple OpenWiki extension marker pairs were detected.",
    );
  }

  const end = endMarker + END.length;
  const nextNewline = content.indexOf("\n", end);
  return {
    start,
    end: nextNewline === -1 ? end : nextNewline + 1,
  };
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

/**
 * Installs the managed OpenWiki extension into the given file path.
 *
 * @param filePath - Absolute destination path.
 * @param entry - Target MCP server command configuration.
 * @param replaceableEntry - Prior configuration that may be cleanly replaced.
 * @returns Whether the file content changed.
 */
export async function installPiExtension(
  filePath: string,
  entry: HostMcpServerCommand,
  replaceableEntry?: HostMcpServerCommand,
): Promise<boolean> {
  const current = (await readOptional(filePath)) ?? "";
  const block = renderPiExtension(entry);
  const range = markerRange(current);

  if (range) {
    const existing = current.slice(range.start, range.end);
    if (hasUnmanagedOpenWikiCode(current, range)) {
      throw new HostIntegrationError(
        "conflict",
        `Refusing to replace a modified OpenWiki extension in ${filePath}.`,
      );
    }
    if (existing === block) return false;
    if (!replaceableEntry || existing !== renderPiExtension(replaceableEntry)) {
      throw new HostIntegrationError(
        "conflict",
        `Refusing to replace a modified OpenWiki extension in ${filePath}.`,
      );
    }
    await writeTextAtomic(
      filePath,
      `${current.slice(0, range.start)}${block}${current.slice(range.end)}`,
    );
    return true;
  }

  if (hasUnmanagedOpenWikiCode(current)) {
    throw new HostIntegrationError(
      "conflict",
      `An unmanaged OpenWiki extension already exists in ${filePath}.`,
    );
  }

  const separator =
    current.length === 0 || current.endsWith("\n\n") ? "" : "\n";
  await writeTextAtomic(filePath, `${current}${separator}${block}`);
  return true;
}

/**
 * Removes the managed OpenWiki extension from the given file path.
 *
 * @param filePath - Absolute destination path.
 * @param entry - Expected MCP server command configuration.
 * @returns Whether the file content changed.
 */
export async function uninstallPiExtension(
  filePath: string,
  entry: HostMcpServerCommand,
): Promise<boolean> {
  const current = await readOptional(filePath);
  if (current === null) return false;
  const range = markerRange(current);
  if (!range) return false;
  if (
    current.slice(range.start, range.end) !== renderPiExtension(entry) ||
    hasUnmanagedOpenWikiCode(current, range)
  ) {
    throw new HostIntegrationError(
      "conflict",
      `Refusing to remove a modified OpenWiki extension from ${filePath}.`,
    );
  }

  await writeTextAtomic(
    filePath,
    `${current.slice(0, range.start)}${current.slice(range.end)}`,
  );
  return true;
}

/**
 * Checks the status of the managed OpenWiki extension in the given file path.
 *
 * @param filePath - Absolute destination path.
 * @param entry - Expected MCP server command configuration.
 * @returns Managed integration status.
 */
export async function getPiExtensionStatus(
  filePath: string,
  entry: HostMcpServerCommand,
): Promise<HostIntegrationStatus> {
  try {
    const current = await readOptional(filePath);
    if (current === null) return "not-installed";
    const range = markerRange(current);
    if (!range) {
      return hasUnmanagedOpenWikiCode(current) ? "modified" : "not-installed";
    }
    return current.slice(range.start, range.end) === renderPiExtension(entry) &&
      !hasUnmanagedOpenWikiCode(current, range)
      ? "installed"
      : "modified";
  } catch {
    return "modified";
  }
}
