import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { detectShallowPages } from "../../src/wiki/graph-maintenance.ts";

// Pages that are wide-but-shallow digests of citations rather than real
// depth should be flagged for rewriting, not splitting. Distinct from
// detectSplitCandidates, which catches pages too BIG to be one page — this
// catches pages too THIN to be useful regardless of size.

describe("detectShallowPages", () => {
  let wikiDir: string;

  afterEach(async () => {
    if (wikiDir) await rm(wikiDir, { recursive: true, force: true });
  });

  async function setupWiki(body: string, generatedAt = "2020-01-01T00:00:00.000Z"): Promise<void> {
    wikiDir = await mkdtemp(path.join(os.tmpdir(), "openwiki-shallow-"));
    await mkdir(path.join(wikiDir, "topics"), { recursive: true });
    const content = `---\ntype: Topic\ntitle: Fleet\ngenerated: { by: "openwiki/0.5.2", at: "${generatedAt}" }\n---\n\n${body}\n`;
    await writeFile(path.join(wikiDir, "topics", "fleet.md"), content, "utf8");
  }

  const manyThinSections = Array.from(
    { length: 8 },
    (_, i) => `## Sub-topic ${i + 1}\n\nOne short paragraph summarizing this sub-topic. #docs-repo/src/area/topic-${i}.mdx`,
  ).join("\n\n");

  test("flags a page with many sections and low words-per-section", async () => {
    await setupWiki(manyThinSections);
    const candidates = await detectShallowPages(wikiDir);
    expect(candidates).toHaveLength(1);
    expect(candidates[0].relativePath).toBe("/topics/fleet.md");
    expect(candidates[0].sections).toHaveLength(8);
  });

  test("leaves a page with few sections alone even if thin", async () => {
    const fewSections = Array.from({ length: 2 }, (_, i) => `## Sub-topic ${i + 1}\n\nShort.`).join("\n\n");
    await setupWiki(fewSections);
    const candidates = await detectShallowPages(wikiDir);
    expect(candidates).toHaveLength(0);
  });

  test("leaves a page with many sections alone if each is substantial", async () => {
    const denseSections = Array.from(
      { length: 8 },
      (_, i) => `## Sub-topic ${i + 1}\n\n${"word ".repeat(200)}`,
    ).join("\n\n");
    await setupWiki(denseSections);
    const candidates = await detectShallowPages(wikiDir);
    expect(candidates).toHaveLength(0);
  });

  test("respects the same cooldown as split — a page this run just touched isn't re-flagged", async () => {
    const runStartedAt = Date.now();
    await setupWiki(manyThinSections, new Date(Date.now() - 30 * 60 * 1000).toISOString());
    const candidates = await detectShallowPages(wikiDir, { runStartedAt });
    expect(candidates).toHaveLength(0);
  });

  test("a page generated by this same run stays eligible despite the cooldown window", async () => {
    const runStartedAt = Date.now() - 5_000;
    await setupWiki(manyThinSections, new Date().toISOString());
    const candidates = await detectShallowPages(wikiDir, { runStartedAt });
    expect(candidates).toHaveLength(1);
  });

  test("maxDensity and minSections are configurable", async () => {
    await setupWiki(manyThinSections);
    expect(await detectShallowPages(wikiDir, { maxDensity: 5 })).toHaveLength(0);
    expect(await detectShallowPages(wikiDir, { minSections: 20 })).toHaveLength(0);
  });
});
