import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { detectSplitCandidates } from "../../src/wiki/graph-maintenance.ts";

// A freshly-split sub-page that still clears the word/section bar must not
// immediately re-qualify for another split on the next pass, or repeated
// runs cascade into severe over-fragmentation. Enforced via a cooldown keyed
// off the page's own OKF `generated.at` timestamp.

const LONG_BODY = Array.from(
  { length: 4 },
  (_, i) => `## Section ${i + 1}\n\n${"word ".repeat(310)}`,
).join("\n\n");

function pageContent(generatedAt: string): string {
  return `---\ntype: Topic\ntitle: Big Topic\ngenerated: { by: "openwiki/0.5.2", at: "${generatedAt}" }\n---\n\n${LONG_BODY}\n`;
}

describe("detectSplitCandidates cooldown", () => {
  let wikiDir: string;

  afterEach(async () => {
    if (wikiDir) await rm(wikiDir, { recursive: true, force: true });
  });

  async function setupWiki(generatedAt: string): Promise<void> {
    wikiDir = await mkdtemp(path.join(os.tmpdir(), "openwiki-split-cooldown-"));
    const topicsDir = path.join(wikiDir, "topics");
    await mkdir(topicsDir, { recursive: true });
    await writeFile(path.join(topicsDir, "big-topic.md"), pageContent(generatedAt), "utf8");
  }

  test("a page generated moments ago is NOT a split candidate, even though it clears the size bar", async () => {
    await setupWiki(new Date().toISOString());
    const candidates = await detectSplitCandidates(wikiDir);
    expect(candidates).toHaveLength(0);
  });

  test("the same oversized page becomes a candidate again once the cooldown has passed", async () => {
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();
    await setupWiki(twoHoursAgo);
    const candidates = await detectSplitCandidates(wikiDir);
    expect(candidates).toHaveLength(1);
    expect(candidates[0].relativePath).toBe("/topics/big-topic.md");
  });

  test("a page with no generated timestamp is not exempted by the cooldown", async () => {
    wikiDir = await mkdtemp(path.join(os.tmpdir(), "openwiki-split-cooldown-"));
    const topicsDir = path.join(wikiDir, "topics");
    await mkdir(topicsDir, { recursive: true });
    const content = `---\ntype: Topic\ntitle: Big Topic\n---\n\n${LONG_BODY}\n`;
    await writeFile(path.join(topicsDir, "big-topic.md"), content, "utf8");

    const candidates = await detectSplitCandidates(wikiDir);
    expect(candidates).toHaveLength(1);
  });

  test("a malformed generated.at value does not crash detection and does not exempt the page", async () => {
    await setupWiki("not-a-real-date");
    const candidates = await detectSplitCandidates(wikiDir);
    expect(candidates).toHaveLength(1);
  });

  test("a page generated by THIS run is a candidate even though it's moments old, when runStartedAt predates it", async () => {
    // The scenario the cooldown must NOT block: graduate a page, then split
    // it in the same pass — generated.at is after this run's own start time,
    // so it isn't a leftover from a previous invocation.
    const runStartedAt = Date.now() - 5_000;
    await setupWiki(new Date().toISOString());
    const candidates = await detectSplitCandidates(wikiDir, { runStartedAt });
    expect(candidates).toHaveLength(1);
  });

  test("a page generated before this run started still gets the cooldown", async () => {
    const runStartedAt = Date.now();
    const thirtyMinutesAgo = new Date(Date.now() - 30 * 60 * 1000).toISOString();
    await setupWiki(thirtyMinutesAgo);
    const candidates = await detectSplitCandidates(wikiDir, { runStartedAt });
    expect(candidates).toHaveLength(0);
  });
});

