import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { OPENWIKI_VERSION } from "./constants.js";
import { isFileNotFoundError } from "./fs-errors.js";

const OPENWIKI_AGENTS_SNIPPET_START = "<!-- OPENWIKI:START -->";
const OPENWIKI_AGENTS_SNIPPET_END = "<!-- OPENWIKI:END -->";
const DEFAULT_CODE_MODE_CRON = "0 8 * * *";

export type CodeModeAutomation = "github" | "gitlab" | "none";

// Root agent-instruction files OpenWiki keeps pointed at the generated wiki.
// Each is created when missing and refreshed in place when already present.
const CODE_MODE_AGENT_FILES = ["AGENTS.md", "CLAUDE.md"];

export async function ensureCodeModeRepoSetup(
  cwd: string,
  automation: CodeModeAutomation = "none",
  cronExpression = DEFAULT_CODE_MODE_CRON,
): Promise<void> {
  if (automation === "github") {
    await writeGitHubActionsWorkflow(cwd, cronExpression);
  } else if (automation === "gitlab") {
    await writeGitLabCiWorkflow(cwd);
  }

  await writeCodeModeAgentSnippets(cwd);
}

async function writeGitHubActionsWorkflow(
  cwd: string,
  cronExpression: string,
): Promise<void> {
  const workflowPath = resolveRepoPath(
    cwd,
    ".github",
    "workflows",
    "openwiki-update.yml",
  );
  await mkdir(path.dirname(workflowPath), { recursive: true });
  await writeFile(
    workflowPath,
    createGitHubActionsWorkflow(cronExpression),
    "utf8",
  );
}

async function writeGitLabCiWorkflow(cwd: string): Promise<void> {
  await writeFile(
    resolveRepoPath(cwd, ".gitlab-ci.yml"),
    createGitLabCiWorkflow(),
    "utf8",
  );
}

async function writeCodeModeAgentSnippets(cwd: string): Promise<void> {
  const snippet = createCodeModeAgentsSnippet();

  await Promise.all(
    CODE_MODE_AGENT_FILES.map((fileName) =>
      writeCodeModeAgentSnippet(resolveRepoPath(cwd, fileName), snippet),
    ),
  );
}

function resolveRepoPath(cwd: string, ...segments: string[]): string {
  const repoRoot = path.resolve(cwd);
  const targetPath = path.resolve(repoRoot, ...segments);

  if (
    targetPath !== repoRoot &&
    !targetPath.startsWith(`${repoRoot}${path.sep}`)
  ) {
    throw new Error(`Refusing to write outside repository root: ${targetPath}`);
  }

  return targetPath;
}

async function writeCodeModeAgentSnippet(
  agentsPath: string,
  snippet: string,
): Promise<void> {
  let currentContent = "";

  try {
    currentContent = await readFile(agentsPath, "utf8");
  } catch (error) {
    if (!isFileNotFoundError(error)) {
      throw error;
    }
  }

  const startIndex = currentContent.indexOf(OPENWIKI_AGENTS_SNIPPET_START);
  const endIndex = currentContent.indexOf(OPENWIKI_AGENTS_SNIPPET_END);
  const nextContent =
    startIndex !== -1 && endIndex !== -1 && endIndex > startIndex
      ? `${currentContent.slice(0, startIndex)}${snippet}${currentContent.slice(endIndex + OPENWIKI_AGENTS_SNIPPET_END.length)}`
      : `${currentContent.trimEnd()}${currentContent.trim().length > 0 ? "\n\n" : ""}${snippet}\n`;

  await writeFile(agentsPath, nextContent, "utf8");
}

function createGitHubActionsWorkflow(cronExpression: string): string {
  return `name: OpenWiki Update

on:
  workflow_dispatch:
  schedule:
    - cron: "${cronExpression}"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Install OpenWiki
        run: npm install --global openwiki@${OPENWIKI_VERSION}

      - name: Run OpenWiki
        run: openwiki code --update --print
        env:
          OPENWIKI_PROVIDER: openrouter
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          OPENWIKI_MODEL_ID: z-ai/glm-5.2
          LANGSMITH_API_KEY: \${{ secrets.LANGSMITH_API_KEY }}
          LANGCHAIN_PROJECT: openwiki
          LANGCHAIN_TRACING_V2: "true"

      - name: Create OpenWiki update pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          add-paths: |
            openwiki
            AGENTS.md
            CLAUDE.md
            .github/workflows/openwiki-update.yml
          branch: openwiki/update
          commit-message: "docs: update OpenWiki"
          title: "docs: update OpenWiki"
          body: |
            Automated OpenWiki documentation update.

            This PR was generated by the scheduled OpenWiki workflow.
`;
}

function createGitLabCiWorkflow(): string {
  return `openwiki_update:
  image: node:22
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  before_script:
    - apt-get update && apt-get install -y git curl
    - npm install --global openwiki@${OPENWIKI_VERSION}
    - git config user.name "\${GITLAB_USER_NAME:-OpenWiki Bot}"
    - git config user.email "\${GITLAB_USER_EMAIL:-openwiki@example.com}"
  script:
    - openwiki code --update --print
    - |
      if git diff --quiet -- openwiki AGENTS.md CLAUDE.md .gitlab-ci.yml; then
        echo "OpenWiki is already up to date."
        exit 0
      fi
    - export OPENWIKI_BRANCH="openwiki/update-\${CI_PIPELINE_ID}"
    - git checkout -b "$OPENWIKI_BRANCH"
    - git add openwiki AGENTS.md CLAUDE.md .gitlab-ci.yml
    - git commit -m "docs: update OpenWiki"
    - git push "https://oauth2:\${OPENWIKI_GITLAB_TOKEN}@\${CI_SERVER_HOST}/\${CI_PROJECT_PATH}.git" "$OPENWIKI_BRANCH"
    - |
      curl --fail --request POST \\
        --header "PRIVATE-TOKEN: \${OPENWIKI_GITLAB_TOKEN}" \\
        --form "source_branch=\${OPENWIKI_BRANCH}" \\
        --form "target_branch=\${CI_DEFAULT_BRANCH}" \\
        --form "title=docs: update OpenWiki" \\
        --form "description=Automated OpenWiki documentation update generated by the scheduled GitLab pipeline." \\
        "\${CI_API_V4_URL}/projects/\${CI_PROJECT_ID}/merge_requests"
  variables:
    OPENWIKI_PROVIDER: openrouter
    OPENWIKI_MODEL_ID: z-ai/glm-5.2
    LANGCHAIN_PROJECT: openwiki
    LANGCHAIN_TRACING_V2: "true"
`;
}

function createCodeModeAgentsSnippet(): string {
  return `${OPENWIKI_AGENTS_SNIPPET_START}

## OpenWiki

This repository uses OpenWiki for recurring code documentation. Start with \`openwiki/quickstart.md\`, then follow its links to architecture, workflows, domain concepts, operations, integrations, testing guidance, and source maps.

The scheduled OpenWiki CI workflow refreshes the repository wiki when configured. Do not hand-edit generated OpenWiki pages unless explicitly asked; prefer updating source code/docs and letting OpenWiki regenerate.

${OPENWIKI_AGENTS_SNIPPET_END}`;
}
